require('packages.main')

require('config.set')
require('config.map')
require('config.miniai')
require('config.telescope')
require('config.undotree')
require('config.treesitter')
require('config.lsp')
require('config.blink')
require('config.theme')
